OFFSIDE-PDA/OFFSIDE

offside/lib/Kleague/kLeague.dart
offside/lib/MainPage/main_page.dart
offside/lib/MyPage/mypage.dart
offside/lib/MyPage/profile.dart
offside/macos/Flutter/GeneratedPluginRegistrant.swift
offside/pubspec.lock
offside/pubspec.yaml
offside/windows/flutter/generated_plugin_registrant.cc
offside/windows/flutter/generated_plugins.cmake

Mypage UI 설정
1. Mypage UI/UX
1. DB연결

Feature {my page} os 30

---

offside/android/app/build.gradle
offside/lib/MainPage/main_page.dart
offside/lib/Schedule/schedule.dart
offside/lib/main.dart
offside/lib/match_schedule.dart
offside/pubspec.yaml

전체 경기 일
1. K리그 1 전체 경기 일정
2. K리그 2 전체 경기 일정
1. 각 팀별 경기 일정

<Feat> :  경기 일정

---

offside/lib/MyPage/mypage.dart
offside/lib/MyPage/profile.dart
offside/lib/data/repository/auth_repository.dart
offside/lib/main.dart
offside/lib/user_view_model.dart

<feat> : 자동로그인

---

offside/lib/Kleague/TeamInfo.dart
offside/lib/Kleague/kLeague.dart
offside/lib/MainPage/main_page.dart
offside/lib/MyPage/mypage.dart
offside/lib/main.dart
offside/macos/Flutter/GeneratedPluginRegistrant.swift
offside/pubspec.yaml
offside/windows/flutter/generated_plugin_registrant.cc
offside/windows/flutter/generated_plugins.cmake

팀 페이지 추가, 마이페이지 버튼추가
1. Navbar 변경
2. 팀 페이지 추가
3. 마이페이지 버튼 추가
1. Appbar, Navbar 변경

Feature {team page} os 45

---

offside/lib/MyPage/mypage.dart
offside/lib/MyPage/myteam.dart

Feature {my team} os 48

---

offside/lib/MyPage/myteam.dart

내 응원팀 경기일정 UI 변경
1. 내 응원팀 경기일정 UI 변경
2. 뒤로가기 버튼 추가
ex) 1. 반응형 디자인

<feat> : Myteam

---

offside/lib/MyPage/mypage.dart
offside/macos/Flutter/GeneratedPluginRegistrant.swift
offside/pubspec.yaml

mypage 반응형 해결
1. 마이페이지 반응형 UI 깨지는 거 해결

<feat> : mypage 반응형 해결

---

offside/lib/MainPage/home_page.dart
offside/lib/Match/matchDetail.dart
offside/lib/MyPage/myTravel.dart
offside/lib/MyPage/mypage.dart
offside/lib/MyPage/myteam.dart

Feat {tour check} os 65

---

offside/android/app/src/main/AndroidManifest.xml
offside/ios/Runner/Info.plist
offside/lib/MainPage/home_page.dart
offside/lib/TourSchedule/tourPlan.dart
offside/lib/TourSchedule/tourSchedule.dart
offside/lib/data/model/tour_model.dart
offside/lib/data/view/tour_view_model.dart
offside/lib/main.dart
offside/pubspec.yaml

여행 일정
1. 현위치 및 홈경기장 마커 표시
2. 여행지 마커 표시
3. 여행 일정 페이지
ex) 1. 반응형 디자인

<Feat> :  여행 일정

---

offside/lib/Kleague/TeamInfo.dart
offside/lib/TourSchedule/tourPlan.dart
offside/lib/data/api/tour_api.dart
offside/lib/data/datasource/tour_data_source.dart

API 호출
1.  api 호출 방식 수정
ex) 1. 반응형 디자인

<Feat> :  api

---

offside/lib/TourSchedule/tourPlan.dart
offside/lib/data/api/tour_api.dart

여행지 리스트 검색창 수정
1. 여행 일정 페이지 여행지 리스트 검색창 수정
ex) 1. 반응형 디자인

<Feat> :  여행 정보 검색

---

offside/lib/MyPage/myTravel.dart
offside/lib/TourSchedule/tourPlan.dart
offside/lib/TourSchedule/tourSchedule.dart
offside/lib/data/api/tour_api.dart
offside/lib/data/datasource/remote_data_source.dart
offside/lib/data/repository/user_info_repository.dart
offside/lib/data/view/user_view_model.dart
offside/pubspec.yaml

내 여행 일정
1. db에 여행일정 저장
2. 저장된 여행일정 불러오기
3. 내 여행 일정 페이지
ex) 1. 반응형 디자인

<Feat> :  여행일정

---

offside/lib/MyPage/myTravel.dart
offside/lib/MyPage/myTravelDetail.dart
offside/lib/TourSchedule/tourPlan.dart
offside/lib/data/api/tour_api.dart
offside/lib/data/datasource/remote_data_source.dart
offside/lib/data/repository/user_info_repository.dart
offside/lib/data/view/user_view_model.dart

내 여행 일정 
1. 내 여행 일정 상세 페이지
2. 여행 일정 수정
ex) 1. 반응형 디자인

<Feat> :  내 여행 일정 수정

---

offside/lib/Kleague/kLeague.dart
offside/lib/MainPage/home_page.dart
offside/lib/Match/match.dart
offside/lib/Match/matchDetail.dart

화면 깨지는거 수정
1. 글자 배치 깨지는거 수정
2. 메인페이지 화면 깨지는거 수정

Feature {u ifix} os 67

---

offside/lib/MyPage/myTravelDetail.dart
offside/lib/TourSchedule/tourPlan.dart
offside/lib/data/api/tour_api.dart

여행 일정 수정 및 삭제
1. 여행 일정 수정 및 삭제
ex) 1. 반응형 디자인

<Feat> :  여행 일정 수정 및 삭제

---

offside/lib/community/Community.dart

<Feat> :  커뮤니티 배경 수정

---

offside/lib/TourSchedule/tourPlan.dart
offside/lib/TourSchedule/tourSchedule.dart

여행 일정 만들기 UI 변경
여행 일정 만들기 UI 변경
마지막 단계 추가 해야 되는거 같음

<feat> : UI 변경

---

offside/lib/MyPage/myTravel.dart

여행 데이터 없는 경우 UI
1. 여행 데이터 없는 경우 UI
ex) 1. 반응형 디자인

<Feat> :  내 여행 일정

---

offside/lib/Kleague/TeamInfo.dart
offside/lib/Kleague/kLeague.dart
offside/lib/MainPage/home_page.dart
offside/lib/data/view/match_view_model.dart

K리그, Home 페이지 기능 개선
1. K리그 페이지 배경색으로 인해 팀 마크 잘 안보이는 기능 개선
2. K리그 teaminfo에서 페이지 스크롤 겹칩 오류 해결
3. Home_page에서 금주의 홈팀 경기 보여주는 부분 축소
4. 가장 가까운 주의 날짜만 받아와 보여주는 기능 추가

Feature {kleague page} os 93

---

offside/lib/Kleague/TeamInfo.dart
offside/lib/Match/match.dart
offside/lib/MyPage/myTravel.dart
offside/lib/MyPage/myTravelDetail.dart
offside/lib/MyPage/profile.dart
offside/lib/TourSchedule/second.dart
offside/lib/TourSchedule/third.dart
offside/lib/TourSchedule/tourPlan.dart
offside/lib/TourSchedule/tourSchedule.dart
offside/lib/data/api/map_api.dart
offside/lib/data/api/tour_api.dart
offside/lib/data/model/tour_model.dart
offside/lib/data/view/match_view_model.dart
offside/lib/login/login.dart
offside/lib/main.dart
offside/pubspec.yaml

내 여행 일정
1. 현위치에서 경기장까지 경로 표시
2. 현위치에서 여행지까지 경로 표시
3. 경기 일정 수정
4. 일정 저장 성공 시 여행 일정 페이지 초기화
ex) 1. 반응형 디자인

Feature {tour map} os 91

---

offside/lib/MyPage/myTravel.dart
offside/lib/MyPage/myTravelDetail.dart
offside/lib/TourSchedule/second.dart
offside/lib/TourSchedule/third.dart
offside/lib/TourSchedule/tourPlan.dart
offside/lib/TourSchedule/tourSchedule.dart
offside/lib/data/api/map_api.dart

오류 수정
1. GPS 권한 메시지
2. 저장한 여행 일정 수정 및 삭제
3. 카카오내비 버튼 추가
ex) 1. 반응형 디자인

<Feat> :  오류 수정

---

offside/lib/TourSchedule/second.dart
offside/pubspec.yaml

----------------------------------------
1. 카카오내비 연동
----------------------------------------
1. 앞으로 할 일

<Feat> :  카카오내비
